In [1]:
import pandas as pd
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
126          127         0       3   
127          128         1       3   
128          129         1       3   
129          130         0       3   
130          131         0       3   
131          132         0       3   
132          133         0       3   
133          134         1       2   
134          135         0       2   
135          136         0       2   
136          137         1       1   
137          138         0       1   
138          139         0       3   
139          140         0       1   
140          141         0       3   
141          142         1       3   
142          143         1       3   
143          144         0       3   
144          145         0       2   
145          146         0       2   
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [3]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  \
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                             Name     Sex   Age  SibSp  Parch  \
146  Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0      0      0   
147              Ford, Miss. Robina Maggie "Ruby"  female   9.0      2      2   
148      Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0      2   
149             Byles, Rev. Thomas Roussel Davids    male  42.0      0      0   
150                    Bateman, Rev. Robert James    male  51.0      0      0   
151             Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                              Meo, Mr. Alfonzo    male  55.5      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
154                         Olsen, Mr. Ole Martin    male   NaN      0      0   
155                   Williams, Mr. Charles Duane    male  51.0      0      1   

          Ticket     Fare Cabin Embarked  
146       350043   7.7958   NaN        S  
147   W./C. 6608  34.3750   NaN        S  
148       230080  26.0000    F2        S  
149       244310  13.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
151       113776  66.6000    C2        S  
152   A.5. 11206   8.0500   NaN        S  
153     A/5. 851  14.5000   NaN        S  
154    Fa 265302   7.3125   NaN        S  
155     PC 17597  61.3792   NaN        C

In [4]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [5]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()


Name   Sex        Ticket        Cabin Embarked
count                          156   156           156           31      155
unique                         156     2           145           28        3
top     Bateman, Rev. Robert James  male  S.O.C. 14879  C23 C25 C27        S
freq                             1   100             2            2      110

In [6]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [7]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [8]:
titanic_train.dtypes[titanic_train.dtypes == "object"]


titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [9]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [10]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

Name   Sex        Ticket        Cabin Embarked
count                          156   156           156           31      155
unique                         156     2           145           28        3
top     Bateman, Rev. Robert James  male  S.O.C. 14879  C23 C25 C27        S
freq                             1   100             2            2      110

In [11]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
5                                     Moran, Mr. James    male   NaN
6                              McCarthy, Mr. Timothy J    male  54.0
7                       Palsson, Master. Gosta Leonard    male   2.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10                     Sandstrom, Miss. Marguerite Rut  female   4.0
11                            Bonnell, Miss. Elizabeth  female  58.0
12                      Saundercock, Mr. William Henry    male  20.0
13                         Andersson, Mr. Anders Johan    male  39.0
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16                                Rice, Master. Eugene    male   2.0
17                        Williams, Mr. Charles Eugene    male   NaN
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19                             Masselmani, Mrs. Fatima  female   NaN
20                                Fynney, Mr. Joseph J    male  35.0
21                               Beesley, Mr. Lawrence    male  34.0
22                         McGowan, Miss. Anna "Annie"  female  15.0
23                        Sloper, Mr. William Thompson    male  28.0
24                       Palsson, Miss. Torborg Danira  female   8.0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
26                             Emir, Mr. Farred Chehab    male   NaN
27                      Fortune, Mr. Charles Alexander    male  19.0
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN
29                                 Todoroff, Mr. Lalio    male   NaN
..                                                 ...     ...   ...
126                                McMahon, Mr. Martin    male   NaN
127                          Madsen, Mr. Fridtjof Arne    male  24.0
128                                  Peter, Miss. Anna  female   NaN
129                                 Ekstrom, Mr. Johan    male  45.0
130                               Drazenoic, Mr. Jozef    male  33.0
131                     Coelho, Mr. Domingos Fernandeo    male  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  female  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0
134                     Sobey, Mr. Samuel James Hayden    male  25.0
135                                 Richard, Mr. Emile    male  23.0
136                       Newsom, Miss. Helen Monypeny  female  19.0
137                        Futrelle, Mr. Jacques Heath    male  37.0
138                                Osen, Mr. Olaf Elon    male  16.0
139                                 Giglio, Mr. Victor    male  24.0
140                      Boulos, Mrs. Joseph (Sultana)  female   NaN
141                           Nysten, Miss. Anna Sofia  female  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  female  24.0
143                                Burke, Mr. Jeremiah    male  19.0
144                         Andrew, Mr. Edgardo Samuel    male  18.0
145                       Nicholls, Mr. Joseph Charles    male  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0
147                   Ford, Miss. Robina Maggie "Ruby"  female   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5
149                  Byles, Rev. Thomas Roussel Davids    male  42.0
150                         Bateman, Rev. Robert James    male  51.0
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. A

In [12]:
sorted(titanic_train["Name"])[5:10:2]# Check the first 15 sorted names

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [13]:
titanic_train["Name"].describe()

count                            156
unique                           156
top       Bateman, Rev. Robert James
freq                               1
Name: Name, dtype: object

In [14]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [15]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh  
0      0         A/5 21171   7.2500   NaN        S  sdffs  
1      0          PC 17599  71.2833   C85        C  sdffs  
2      0  STON/O2. 3101282   7.9250   NaN        S  sdffs  
3      0            113803  53.1000  C123        S  sdffs  
4      0            373450   8.0500   NaN        S  sdffs

In [17]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [18]:
titanic_train.dtypes# Check number of unique cabins

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
sudh            object
dtype: object

In [19]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
5      0
6      0
7      0
8      1
9      1
10     1
11     1
12     0
13     0
14     0
15     1
16     0
17     1
18     0
19     1
20     0
21     1
22     1
23     1
24     0
25     1
26     0
27     0
28     1
29     0
      ..
126    0
127    1
128    1
129    0
130    0
131    0
132    0
133    1
134    0
135    0
136    1
137    0
138    0
139    0
140    0
141    1
142    1
143    0
144    0
145    0
146    1
147    0
148    0
149    0
150    0
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [20]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
5      0
6      0
7      0
8      1
9      1
10     1
11     1
12     0
13     0
14     0
15     1
16     0
17     1
18     0
19     1
20     0
21     1
22     1
23     1
24     0
25     1
26     0
27     0
28     1
29     0
      ..
126    0
127    1
128    1
129    0
130    0
131    0
132    0
133    1
134    0
135    0
136    1
137    0
138    0
139    0
140    0
141    1
142    1
143    0
144    0
145    0
146    1
147    0
148    0
149    0
150    0
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [21]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [22]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [23]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [24]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [25]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin


[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [26]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   sudh  
0      0         A/5 21171   7.2500     n        S  sdffs  
1      0          PC 17599  71.2833     C        C  sdffs  
2      0  STON/O2. 3101282   7.9250     n        S  sdffs  
3      0            113803  53.1000     C        S  sdffs  
4      0            373450   8.0500     n        S  sdffs

In [27]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17      True
18     False
19      True
20     False
21     False
22     False
23     False
24     False
25     False
26      True
27     False
28      True
29      True
       ...  
126     True
127    False
128     True
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140     True
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [28]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [29]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [30]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked   sudh  
27  19.0      3      2  19950  263.0     C        S  sdffs  
88  23.0      3      2  19950  263.0     C        S  sdffs

In [31]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [32]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71], dtype=int64),)

In [33]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked   sudh  Family  
59  11.0      5      2  CA 2144  46.9     n        S  sdffs       7  
71  16.0      5      2  CA 2144  46.9     n        S  sdffs       7