In [2]:
import numpy as np

In [3]:
type(np.array(["vbvhb",2,3]))

numpy.ndarray

In [10]:
#upcasting
np.array([1,2,3.3,4.0])

array([1. , 2. , 3.3, 4. ])

In [5]:
#two dimensions
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
#Minimum Dimensions 2
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [8]:
#dtype
np.array([1,2,3,],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [11]:
#Data- type consisting of more than one element:
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i4')])

In [18]:
type(x[1][1])

numpy.int32

In [19]:
#create an array fro msub-classes:
np.mat(np.array([[1,2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [20]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [24]:
type(np.mat('1 2; 3 4'))

numpy.matrix

In [25]:
type(np.mat)

function

# numpy.asarray

In [26]:
#convert the input to an array

In [27]:
#convert a list into an array

In [28]:
a=[1,2]
type(a)

list

In [29]:
type(np.asarray(a))

numpy.ndarray

In [30]:
a=np.array([1,2])
type(a)

numpy.ndarray

In [31]:
np.asarray(a) is a

True

In [32]:
#if dtype is set, array is copied only if dtype does not match:
a= np.array([1,2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [35]:
np.asarray(a, dtype=np.float64) is a

False

In [37]:
np.asanyarray(a) is a

True

In [38]:
y =x 
z=np.copy(x)

In [40]:
y[0]=100

array([(100, 100), (  3,   4)], dtype=[('a', '<i2'), ('b', '<i4')])

In [41]:
id(x[0])

2139590272984

# numpy.fromfunction 

In [42]:
#construct ana rray by executing a function over each coordinate.

In [43]:
np.fromfunction(lambda i,j: i==j, (3,3), dtype=int)


array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [44]:
np.fromfunction(lambda i,j:i+j, (3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [46]:
#Create a new 1-dimensional aray from an iterable object.
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001F229829480>

In [47]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [50]:
# A new 1-D array initialized from text data in a string
a= np.fromstring('234 234', sep=' ')
a

array([234., 234.])

In [51]:
#How to create a record array from a (flat) list of arrays
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xxx','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [54]:
r= np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xxx', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [58]:
type(r)

numpy.recarray

In [59]:
print(r[1]["a"])

2


# data types

In [60]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [61]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [62]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [63]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# # arange and linspace

In [71]:
print("a series of number:",type (np.arange(5,16)))
np.arange(5,16,2.3)

a series of number: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [70]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [68]:
list(range(50,-1,5))

[]

In [72]:
print("numbers spaced apart by 2:", np.arange(0,11,2))#number spaced apart by 2

numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [73]:
print("numbers spaced apart by float:", np.arange(0,11,2.5))#number spaced apart by 2.5

numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [74]:
print("Every 5th number from 50 in reverse order\n", np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [75]:
print("21 linearly spaced number between 1 and 5\n--------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced number between 1 and 5
--------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix Creation

In [76]:
print("Vector of zeroes\n-------")
print(np.zeros(5))

Vector of zeroes
-------
[0. 0. 0. 0. 0.]


In [77]:
print("Matrix of zeros\n-------------")
print(np.zeros((3,4,8)))

Matrix of zeros
-------------
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]]


In [78]:
print("Vector of ones\n----------")
print(np.ones(5))

Vector of ones
----------
[1. 1. 1. 1. 1.]


In [79]:
print("Matrix of ones\n-----------")
print(np.ones((5,2,8)))

Matrix of ones
-----------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [82]:
print("Matrix of ones\n-----------")
print(6+np.ones((3,5)))

Matrix of ones
-----------
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [84]:
print("Empty matrix\n------------\n",np.empty((3,5)))

Empty matrix
------------
 [[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [86]:
mat1=np.eye(6)
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (6, 6)
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [87]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [88]:
np.linspace(2.0, 3.0, num=5, endpoint= False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [89]:
np.linspace(2.0, 3.0, num=50, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [95]:
np.logspace(2.0,3.0, num=4, base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [91]:
np.logspace(2.0, 3.0, num=4, endpoint= False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [105]:
x=np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.diag(x)

array([ 0,  5, 10, 15])

In [107]:
np.diag(x,k=1)

array([ 1,  6, 11])

In [108]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [109]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [110]:
#create a two-dimensional array with the flattened inputas as a diagonal
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [111]:
#an array with ones at and below the given diagonal and zeros elsewhere.

In [112]:
np.tri(3,5,3, dtype=int)

array([[1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [125]:
np.tri(3,5, k=3)

array([[1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [130]:
#return a lower triangle of an  array
np.tril([[1,2,3],[4,5,6,],[7,8,9]],1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
#return upper triangle of an array
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

# Random Number Generation

In [162]:
print("Random Number Generation(from Uniform Distribution)")
phhh=(np.random.rand(2,3))
print(phhh)

#print(np.random.rand(2,3))

Random Number Generation(from Uniform Distribution)
[[0.20018814 0.60954334 0.0939157 ]
 [0.17426118 0.02468074 0.40552071]]


In [158]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.56687114 -1.65872007  0.20370425]
 [ 2.69642169 -0.08157366 -0.32856196]
 [-0.53654888  0.82677842  0.37306534]
 [ 0.92506501  1.6924734   0.47621187]]


In [159]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 1

Random integer matrix


In [140]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[11 82 39 75]
 [70 49 68 50]
 [11 55 56 80]
 [61 25 29 59]]

20 samples drawn from a dice throw: [4 6 2 4 5 4 3 3 1 6 4 5 6 6 2 4 1 3 5 4]


# Reshaping

In [165]:
from numpy.random import randint as ri
a=ri(1,100,30)
b=a.reshape(2,3,5)
c=a.reshape(6,-19878)

print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)
c


a looks like
 -------------------- 
 [ 8 51 92 13 27 69 44 43 17 50  3 50  8 70 99 84 56 93 34 72 56 28 25 82
 45  1 58 13 66 83] 
 --------------------

b looks like
 -------------------- 
 [[[ 8 51 92 13 27]
  [69 44 43 17 50]
  [ 3 50  8 70 99]]

 [[84 56 93 34 72]
  [56 28 25 82 45]
  [ 1 58 13 66 83]]] 
 --------------------

c looks like
 -------------------- 
 [[ 8 51 92 13 27]
 [69 44 43 17 50]
 [ 3 50  8 70 99]
 [84 56 93 34 72]
 [56 28 25 82 45]
 [ 1 58 13 66 83]] 
 --------------------


array([[ 8, 51, 92, 13, 27],
       [69, 44, 43, 17, 50],
       [ 3, 50,  8, 70, 99],
       [84, 56, 93, 34, 72],
       [56, 28, 25, 82, 45],
       [ 1, 58, 13, 66, 83]])

In [166]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [61 58 58 65 55 32 88 12 21 76]

Here is the sorted vector
 -------------------------------------------------- 
 [12 21 32 55 58 58 61 65 76 88]


In [167]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[18 41 85 89 96]
 [ 9 28 37 48 91]
 [ 1 22 32 56 67]
 [ 6 14 56 81 86]
 [16 30 55 80 98]]


array([[96, 89, 85, 41, 18],
       [ 9, 91, 37, 48, 28],
       [56, 22, 67, 32,  1],
       [56, 14,  6, 81, 86],
       [55, 98, 16, 80, 30]])

In [168]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 98
Max of b: 99


array([[[ 8, 51, 92, 13, 27],
        [69, 44, 43, 17, 50],
        [ 3, 50,  8, 70, 99]],

       [[84, 56, 93, 34, 72],
        [56, 28, 25, 82, 45],
        [ 1, 58, 13, 66, 83]]])

In [169]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [0 1 2 4 1]
Max of b location: 14
Max of c location: 14


# Indexing and slicing

In [170]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [171]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [172]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [173]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [175]:
print("3 Elements from last backwards are:", arr[-1:-6:2])

3 Elements from last backwards are: []


In [176]:
arr=np.arange(0,21,2)
print("new array:", arr)

new array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [177]:
print("Elements at 2nd, 4th and 9th index are:", arr[[2,4,9]])

Elements at 2nd, 4th and 9th index are: [ 4  8 18]


In [179]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
#mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[25 58 41 42 80]
 [10 71 38 12 27]
 [61 87 19 62 58]]


array([[12, 27],
       [62, 58]])

In [180]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 71


array([[25, 58, 41, 42, 80],
       [10, 71, 38, 12, 27],
       [61, 87, 19, 62, 58]])

In [181]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 38

Row or column extract
----------------------


In [186]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])
mat

Entire row at index 2: [61 87 19 62 58]
Entire column at index 3: [42 12 62]


array([[25, 58, 41, 42, 80],
       [10, 71, 38, 12, 27],
       [61, 87, 19, 62, 58]])

In [189]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:6])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[12 27]
 [62 58]]


In [190]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[58 42]
 [71 12]]


# Subsetting

In [191]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[75 63 31 22 56]
 [60 13 31 57 75]
 [68 46 37 45 63]]


array([[ True,  True, False, False,  True],
       [ True, False, False,  True,  True],
       [ True, False, False, False,  True]])

In [193]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [75 63 56 60 57 75 68 63]


# Slicing

In [198]:
mat=np.array(([11,12,13],[21,22,23],[32,32,33]))
print("original Matrix ")
print(mat)

original Matrix 
[[11 12 13]
 [21 22 23]
 [32 32 33]]


In [199]:
mat_slice=mat[:2,:2]
print("\nsliced matrix")
print(mat_slice)
print("\nChange the sliced mtrix")


sliced matrix
[[11 12]
 [21 22]]

Change the sliced mtrix


In [201]:
mat_slice[0,0]=111111
print(mat_slice)

[[111111     12]
 [    21     22]]


# Universal Functions

In [209]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n ",'-'*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",'-'*50,"\n",mat2)



1st Matrix of random single-digit numbers
  -------------------------------------------------- 
 [[1 4 1]
 [3 3 7]
 [1 6 5]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 6 9]
 [8 3 2]
 [5 6 8]]


In [210]:
mat1*mat2

array([[ 2, 24,  9],
       [24,  9, 14],
       [ 5, 36, 40]])

In [211]:
#matrix multiplication
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[39 24 25]
 [65 69 89]
 [75 54 61]]


In [213]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\zeesh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [214]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[101 104 101]
 [103 103 107]
 [101 106 105]]


In [215]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[  1  64   1]
 [ 27  27 343]
 [  1 216 125]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[  1  64   1]
 [ 27  27 343]
 [  1 216 125]]


# Broadcasting

In [217]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [218]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [220]:
#create a rank 1 ndarray with 3 values
add_rows=np.array([1,0,2,5])
print(add_rows)

[1 0 2 5]


In [255]:
y=start + add_rows # add to each row pf ' start' using broadcasting 
y
np.vstack((y,[2,2,2,5]))

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [  2.,   2.,   2.,   5.]])

In [224]:
#create an ndarray which is 4 X 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [228]:
#add to each column of 'start' using broadcasting
y=start + add_cols
y

array([[100., 100., 100., 100.],
       [101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.]])

In [230]:
#this will just broadcast in both dimensions
add_scalar=np.array([100])
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [231]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[6 5 4]
 [9 3 1]
 [2 2 8]]

2nd Matrix of random single-digit numbers
------------
 [[3 9 8]
 [6 1 4]
 [8 5 6]]


In [232]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.44948974 2.23606798 2.        ]
 [3.         1.73205081 1.        ]
 [1.41421356 1.41421356 2.82842712]]


In [233]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[4.03428793e+02 1.48413159e+02 5.45981500e+01]
 [8.10308393e+03 2.00855369e+01 2.71828183e+00]
 [7.38905610e+00 7.38905610e+00 2.98095799e+03]]


In [234]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.77815125 0.69897    0.60205999]
 [0.95424251 0.47712125 0.        ]
 [0.30103    0.30103    0.90308999]]
[[6 5 4]
 [9 3 1]
 [2 2 8]]
[[3 9 8]
 [6 1 4]
 [8 5 6]]


In [237]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))

#  this is same as modulus
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 5 4]
 [3 0 1]
 [2 2 2]]


array([[0, 5, 4],
       [3, 0, 1],
       [2, 2, 2]], dtype=int32)

In [238]:
print("\nCombination of functions by showing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by showing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [251]:
A = np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])